name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input.
  
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  
  - type: dropdown
    id: component
    attributes:
      label: Which component would this affect?
      options:
        - CLI
        - VS Code Extension
        - Core Library
        - Documentation
        - Other
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to work on this feature?
      options:
        - label: I would like to implement this feature
        - label: I need help implementing this feature
        - label: I'm just suggesting the idea
